x = int(input("x = "))
y = int(input("y = "))
a = str(x+y)
b = str(x-y)
c = str(x*y)
d = str(x/y)
print(str(x),"+",str(y),"=",a)
print(str(x),"-",str(y),"=",b)
print(str(x),"*",str(y),"=",c)
print(str(x),"/",str(y),"=",d)